# Generated by Django 2.0.6 on 2018-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180627_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone1',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='zipcode',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
