# Generated by Django 2.0.6 on 2018-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180630_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
