# Generated by Django 2.0.6 on 2018-07-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20180701_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentinstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(null=True)),
                ('instrument', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
