# Generated by Django 2.0.6 on 2018-07-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentinstrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinstrument',
            name='studentID',
        ),
        migrations.AddField(
            model_name='studentinstrument',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
