# Generated by Django 2.0.6 on 2018-07-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_email2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
